### ISSUE TITLE
Failed to activate the atom-bugs package

### ISSUE THREAD

**Issue by FCNB** [willyelm/xatom-debug#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-bugs](https://github.com/atom-bugs/atom-bugs) package 1.2.6

### Stack Trace

Failed to activate the atom-bugs package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/atom-bugs/lib/main.js:16:9)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
  2x -0:43.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bugs 1.2.6 
atom-html-preview 0.1.22 
atom-package-deps 4.5.0 
autoclose-html 0.24.0 
autocomplete-paths 1.0.5 
jquery-snippets 11.0.0 
node_modules undefined 
```

**Comment by willyelm** [comment]
Please let me know if in the latest version it still happens. Thank you!

**Comment by yamsellem** [comment]
@willyelm I've got this error and #1 too with `atom-bugs 1.2.17`, `atom-bugs-nodejs 0.5.4`, and `atom 1.15.0` (_so, I cannot give you feedback right now on #2_ ;-) )

**Comment by willyelm** [comment]
Found the issue, please update and try again.
