### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by danielcherubini** [willyelm/xatom-debug#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.10

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/danielcherubini/.atom/packages/xatom-debug/lib/editor/editor-manager.js:221

TypeError: Cannot read property 'getBoundingClientRect' of null
  at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:292:35)
  at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:329:39)
  at /packages/xatom-debug/lib/editor/editor-manager.js:219:47)

```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.4 
atom-jade 0.3.0 
build 0.68.0 
builder-go 1.0.1 
busy 0.7.0 
docblockr 0.11.0 
docker 0.7.0 
editorconfig 2.2.2 
emmet 2.4.3 
flow-ide 1.6.0 
go-config 1.2.4 
go-debug 1.5.0 
go-get 2.1.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
godoc 1.1.1 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.2 
js-hyperclick 1.11.0 
language-babel 2.68.0 
language-docker 1.1.8 
language-elixir 0.19.0 
language-env 0.2.0 
language-graphql 0.9.0 
language-groovy 0.7.0 
language-ini 1.19.0 
language-leaf 0.1.1 
language-lua 0.9.11 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-pico8 1.0.0 
language-pug 0.0.21 
language-rust 0.4.11 
language-scala 1.1.8 
language-swift 0.5.0 
language-systemd 0.1.1 
language-thrift 1.0.2 
language-vue 0.23.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-javac 1.9.4 
linter-pug-lint 0.2.0 
MagicPython 1.0.11 
merge-conflicts 1.4.5 
mocha-test-runner 1.0.0 
node-debugger 1.10.1 
nuclide 0.241.0 
nuclide-format-js 0.0.36 
nuclide-test-runner-jest 0.3.0 
path-hyperclick 0.3.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
xatom-debug 1.6.10 
xatom-debug-nodejs 0.9.3 
```

**Comment by zaaack** [comment]
Hit this problem, too. This happened when I open an image.

**Comment by anshulk** [comment]
Started happening with me after installing nuclide.

**Comment by two7sclash-zz** [comment]
still happening...

**Comment by galmis** [comment]
still happening

**Comment by victorperin** [comment]
still happening...

**Comment by prajjwaldimri** [comment]
Happening on markdown previews too.

**Comment by pk75** [comment]
Happens after installing nuclide

**Comment by azhar22k** [comment]
Still happening

**Comment by mira13** [comment]
Still exists, hitting it on markdown preview
