### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kevitan** [willyelm/xatom-debug#39]
This is every time I select something in the editor for a `.ts` file, the following stack trace is shown:

```TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2286:33)
    at HTMLElement.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:247:32)
    at EditorManager.getEditorPositionFromEvent (/Users/me/.atom/packages/xatom-debug/lib/editor/editor-manager.js:222:45)
    at EditorManager.listenExpressionEvaluations (/Users/me/.atom/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLElement.expressionHandler (/Users/me/.atom/packages/xatom-debug/lib/editor/editor-manager.js:159:57)```

**Comment by kevitan** [comment]
this is still an issue after 084e51a
