### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by achimbode** [willyelm/xatom-debug#51]
Something in Atom wanted to update. I gave the firewall permission and now: They're popping up in hundrets...

[Enter steps to reproduce:]

1. automatic update of the xatom-debug package

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/achimbode/.atom/packages/xatom-debug/lib/editor/editor-manager.js:221

TypeError: Cannot read property 'getBoundingClientRect' of null
    at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:221:31)
    at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLDivElement.expressionHandler (/packages/xatom-debug/lib/editor/editor-manager.js:159:57)
```

### Commands

```
  2x -6:52.1.0 editor:newline (input.hidden-input)
     -6:42.4.0 snippets:next-tab-stop (input.hidden-input)
     -6:42.4.0 autocomplete-plus:confirm (input.hidden-input)
     -6:42.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -6:40.1.0 snippets:next-tab-stop (input.hidden-input)
     -6:40.1.0 autocomplete-plus:confirm (input.hidden-input)
     -6:39.2.0 editor:newline (input.hidden-input)
     -6:33.6.0 snippets:next-tab-stop (input.hidden-input)
     -6:33.6.0 autocomplete-plus:confirm (input.hidden-input)
     -6:33.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -6:29.3.0 core:save (input.hidden-input)
     -2:10.8.0 find-and-replace:show (input.hidden-input)
     -2:08.7.0 core:confirm (input.hidden-input)
  3x -1:58 core:backspace (input.hidden-input)
     -1:46.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-html-preview 0.2.5 
atom-ide-ui 0.6.0 
atom-python-run 0.9.3 
autoclose-html 0.23.0 
autocomplete-python 1.10.3 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
intentions 1.1.5 
jshint 1.8.6 
language-babel 2.79.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.10 
node-debugger 1.10.1 
platformio-ide-terminal 2.7.0 
prettier-atom 0.41.0 
pretty-json 1.6.4 
python-indent 1.1.4 
python-tools 0.6.9 
react 0.17.0 
script 3.17.3 
todo-show 2.1.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by t0cc** [comment]
The same for me. They started popping up when I opend a picture in Atom to preview and I pressed the **Zoom to fit** button there.

![screenshot_20171208_222951](https://user-images.githubusercontent.com/26163366/33785917-6fd13052-dc67-11e7-8500-d75299308aa1.png)
