### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by michelleinez** [willyelm/xatom-debug#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.5
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.11

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:646:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:643:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:586:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:561:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:506:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2401:18)
    at HTMLElement.screenPositionForPixelPosition (/app.asar/src/text-editor-element.js:247:32)
    at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:222:45)
    at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLElement.expressionHandler (/packages/xatom-debug/lib/editor/editor-manager.js:159:57)
```

### Commands

```
```

### Non-Core Packages

```
atom-ethereum-interface 2.0.0 
auto-indent-file 0.2.0 
autoclose-html 0.23.0 
emmet-jsx-css-modules 1.0.0 
git-blame 1.1.1 
git-time-machine 1.5.6 
language-javascript-jsx 0.3.7 
pretty-json 1.5.1 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by codirix** [comment]
I have this problem when i open the **doc api** package for a describe a elements

**Comment by ciphers0** [comment]
hello i have this problem when i open the **doc api** package for a describe a elements
