### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by roy651** [willyelm/xatom-debug#66]
[Enter steps to reproduce:]

1. Observed the content of a zip file

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.1
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/il239838/.atom/packages/xatom-debug/lib/editor/editor-manager.js:221

TypeError: Cannot read property 'getBoundingClientRect' of null
    at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:221:32)
    at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLDivElement.expressionHandler (/packages/xatom-debug/lib/editor/editor-manager.js:159:57)
```

### Commands

```
     -5:25.9.0 project-find:show (input.hidden-input)
     -5:24.9.0 core:paste (input.hidden-input)
     -5:24.4.0 core:confirm (input.hidden-input)
     -5:14.7.0 project-find:show (input.hidden-input)
     -5:12.5.0 core:confirm (input.hidden-input)
     -4:26.9.0 project-find:show (div.results-view.focusable-panel)
  2x -4:23.9.0 core:backspace (input.hidden-input)
     -4:22.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-bugs-syntax 1.9.3 
atom-bugs-ui 1.8.4 
atom-ternjs 0.18.3 
autocomplete-modules 2.2.0 
busy-signal 1.4.3 
file-icons 2.1.24 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
hyperclick 0.1.5 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.13.3 
last-cursor-position 0.9.3 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
node-debugger 1.10.1 
pretty-json 2.0.3 
project-manager 3.3.6 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by josemartinez111** [comment]
Help me im a newb!

**Comment by Teddy95** [comment]
I've got the same error when I use the build-in markdown preview.
