### ISSUE TITLE
Uncaught TypeError: editor.element.getScrollTop is not a function

### ISSUE THREAD

**Issue by edalee** [willyelm/xatom-debug#81]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.13.6
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.11

### Stack Trace

Uncaught TypeError: editor.element.getScrollTop is not a function

```
At /Users/edwardlee/.atom/packages/xatom-debug/lib/editor/editor-manager.js:223

TypeError: editor.element.getScrollTop is not a function
    at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:223:62)
    at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLDivElement.expressionHandler (/packages/xatom-debug/lib/editor/editor-manager.js:159:57)
```

### Commands

```
     -2:07.2.0 core:paste (input.hidden-input)
     -1:43 markdown-preview:toggle (input.hidden-input)
     -1:24.3.0 core:select-all (input.hidden-input)
     -1:23.2.0 core:cut (input.hidden-input)
     -1:16.1.0 application:new-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:14.5.0 core:paste (input.hidden-input)
     -0:56.7.0 markdown-preview:toggle (input.hidden-input)
     -0:20.8.0 xatom-debug:stop (input.hidden-input)
```

### Non-Core Packages

```
atom-code-syntax 0.3.1 
atom-code-ui 0.4.4 
goto 1.8.3 
goto-definition 1.3.4 
pp-markdown 0.0.2 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by edalee** [comment]
Sorry seems to be a duplicate, I will close this.
