### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by PaulPR-44** [willyelm/xatom-debug#82]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [xatom-debug](https://github.com/willyelm/xatom-debug) package 1.6.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /home/paul/.atom/packages/xatom-debug/lib/editor/editor-manager.js:221

TypeError: Cannot read property 'getBoundingClientRect' of null
    at EditorManager.getEditorPositionFromEvent (/packages/xatom-debug/lib/editor/editor-manager.js:221:32)
    at EditorManager.listenExpressionEvaluations (/packages/xatom-debug/lib/editor/editor-manager.js:252:35)
    at HTMLDivElement.expressionHandler (/packages/xatom-debug/lib/editor/editor-manager.js:159:57)
```

### Commands

```
     -9:14.5.0 editor:newline (input.hidden-input)
     -9:14.1.0 core:move-up (input.hidden-input)
     -9:13.6.0 snippets:next-tab-stop (input.hidden-input)
     -9:13.6.0 snippets:expand (input.hidden-input)
     -9:13.6.0 editor:indent (input.hidden-input)
     -9:09.3.0 core:save (input.hidden-input)
  2x -4:10.7.0 core:copy (input.hidden-input)
     -1:02.8.0 tree-view:add-file (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:55.8.0 core:backspace (input.hidden-input)
     -0:54.7.0 core:confirm (input.hidden-input)
     -0:48.6.0 core:paste (input.hidden-input)
     -0:46.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-discord 2.0.2 
atom-terminal 0.8.0 
branch-status 0.8.3 
file-icons 2.1.47 
gpp-compiler 3.0.7 
linter 3.3.0 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-ui-default 3.3.0 
teletype 0.13.4 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by cbarth1530** [comment]
bump
